### ISSUE TITLE
Just wandering

### ISSUE THREAD

**Issue by jeedee23** [Makeroni/Eye-of-Horus#1]
Is this project in further development elsewhere? I have a disabled girlfriend and it would be interesting if she could command with her eyes.

**Comment by B0RJA** [comment]
After the initial built during the NASA Space Apps Challenge, the project was further developed for the semi-finals of the UAE AI and Robotics Award. If you want to see the latest version in action, one of the group members showed it off in a TEDx talk ([video](https://youtu.be/VuZzOhVhWN8?t=579)).The device is still in prototype phase but we can share the source code if it is useful to you. On the other hand, as result of the project we met people with disabilities who use commercial eye tracking systems like irisbond on a daily basis. The hardware is closed but it allows to control the mouse with the eye and this opens the door to develop custom software to control anything.

**Comment by jeedee23** [comment]
Hi,
Yes I know of those hardware systems, but they are soooo expensive, there
are a few DIY projects but all seem to have dropped of the surface of the
earth, this makes me thinking it has been bought out.
The hardware is one thing, but of course, the software is ALL. The built-in
'windows-eye-tracking' works with cheap systems too, but as you mentioned,
a system that 'does it all' would be ideal.
Then again, on the other hand, our insurance pay back a lot of those
systems, so the 'money-making-industry' which is a part of the gigantic
medical, pharmaceutical, prosthetic, a.s.o. world, will profit a long time
from this advantage.

There is another side to: the gaming world. The same device that costs
5000€ for a disabled person, costs around 250 euro for a gamer.

So yes, if you can share the source code, I'll be glad to check it out

Thanks a lot
Johan

Op wo 17 aug. 2022 om 20:52 schreef B0RJA ***@***.***>:

**Comment by B0RJA** [comment]
I have sent you a gitlab invitation link to your email

**Comment by jeedee23** [comment]
Got it, thanks!




Op do 18 aug. 2022 om 07:35 schreef B0RJA ***@***.***>:

**Comment by jeedee23** [comment]
Is it possible that the gitlab project is empty?


Op do 18 aug. 2022 om 07:35 schreef B0RJA ***@***.***>:
